# Tensor network tutorial

In [1]:
import numpy as np
import  datetime

In [4]:
datetime.datetime.now()+datetime.timedelta(days=100)

datetime.datetime(2024, 9, 6, 15, 34, 56, 904562)


# T1.1: Diagrammatic notation

In [2]:
# Let's initialize some tensors in Python/Numpy

# vetor linha
v1 = np.random.rand(1, 2)

#vetor coluna
v2 = np.random.rand(2, 1)

# identity matrix, order 2, dims: 5-by-5 
identity_in_5_order = np.eye(5, 5)

# tensor of 1's, order 4, dims: 2-by-4-by-2-by-4
ones_in_4_order = np.ones((2, 4, 2, 4))

# matrix of 0's, order 2, dims: 3-by-5
zeroes_2_order = np.zeros((3, 5))

# initialize complex random tensor
complex_tensor = np.random.rand(2, 3, 4) + 1j*np.random.rand(2, 3, 4)

In [3]:
v1, v1[0][0], v1[0][1]

(array([[0.14237081, 0.14627598]]), 0.14237080694844984, 0.14627598036930545)

In [4]:
v2, v2[0][0], v2[1][0]

(array([[0.76228925],
        [0.56540378]]),
 0.7622892450752663,
 0.5654037776628551)

In [5]:
A = np.array([[1, 0],
              [0, 1]])

B= np.array([[1, 0],
              [0, -1]])

np.dot(A,B)

## T1.1.1: simple contraction of index

In [29]:
# Fixar a semente para o gerador de números aleatórios
np.random.seed(42)

# Criar tensores aleatórios
A = np.random.rand(3, 4, 5)
B = np.random.rand(3, 3, 6)
C = np.random.rand(6, 5, 3)

# Usando np.einsum para a mesma operação
result = np.einsum('iln,nmk -> ilmk', B, C)

print("Forma do tensor B:", B.shape) 
print("Forma do tensor C:", C.shape)  
print("Forma do resultado B @ C:", result.shape)  

result2 = np.einsum('ljm,ilmk -> ijk',A, result) 

print("Forma do tensor A:", A.shape)  
print("Forma do resultado B @ C:", result.shape)  
print("Forma do resultado A@ B @ C:", result2.shape)  

Forma do tensor B: (3, 3, 6)
Forma do tensor C: (6, 5, 3)
Forma do resultado B @ C: (3, 3, 5, 3)
Forma do tensor A: (3, 4, 5)
Forma do resultado B @ C: (3, 3, 5, 3)
Forma do resultado A@ B @ C: (3, 4, 3)


# T1.2: Permute and reshape operations

In [42]:
##### Ex.1.2(a): Transpose
# argumento são as dimensões do tensor
A = np.random.rand(2, 4, 3)

# argumento é como queremos permutar os indices
Atilda = A.transpose(1, 2, 0)

In [43]:
A.shape, Atilda.shape

((2, 4, 3), (4, 3, 2))

In [44]:
A

array([[[0.99663684, 0.55543171, 0.76898742],
        [0.94476573, 0.84964739, 0.2473481 ],
        [0.45054414, 0.12915942, 0.95405103],
        [0.60617463, 0.22864281, 0.67170068]],

       [[0.61812824, 0.35816272, 0.11355759],
        [0.6715732 , 0.5203077 , 0.77231839],
        [0.5201635 , 0.8521815 , 0.55190684],
        [0.56093797, 0.8766536 , 0.40348287]]])

In [45]:
Atilda

array([[[0.99663684, 0.61812824],
        [0.55543171, 0.35816272],
        [0.76898742, 0.11355759]],

       [[0.94476573, 0.6715732 ],
        [0.84964739, 0.5203077 ],
        [0.2473481 , 0.77231839]],

       [[0.45054414, 0.5201635 ],
        [0.12915942, 0.8521815 ],
        [0.95405103, 0.55190684]],

       [[0.60617463, 0.56093797],
        [0.22864281, 0.8766536 ],
        [0.67170068, 0.40348287]]])

In [46]:
##### Ex.1.2(a): Transpose
# argumento são as dimensões do tensor
A = np.random.rand(2, 4, 3, 2)

# argumento é como queremos permutar os indices
Atilda = A.transpose(3, 0, 1, 2)

result2 = np.einsum('jklm, mjkl', A, Atilda) 
result3 = np.einsum('jklm, jmkl', A, Atilda) 
result2, result3

In [49]:
A.shape, Atilda.shape

((2, 4, 3, 2), (2, 2, 4, 3))

In [58]:
# Ex.1.2(b):Reshape
B = np.random.rand(4,4,4)
Btilda = B.reshape(4, 4**2)

In [62]:
B.shape, Btilda.shape

((4, 4, 4), (4, 16))

In [63]:
B

array([[[0.12063587, 0.46077877, 0.20633372, 0.36426986],
        [0.50341727, 0.69039483, 0.03931214, 0.7994104 ],
        [0.62790039, 0.08175903, 0.87357862, 0.9208724 ],
        [0.06107796, 0.27687765, 0.80620128, 0.74825969]],

       [[0.18452102, 0.20934932, 0.3704721 , 0.48452299],
        [0.61825477, 0.36891364, 0.46253472, 0.74747094],
        [0.0366832 , 0.25243694, 0.71334959, 0.89520684],
        [0.51167744, 0.53211349, 0.10717201, 0.44741237]],

       [[0.53261727, 0.2424705 , 0.26924323, 0.37728416],
        [0.0200712 , 0.32207917, 0.21144801, 0.32749735],
        [0.11976213, 0.89052728, 0.59359245, 0.67910232],
        [0.78917124, 0.4984422 , 0.08692029, 0.53710654]],

       [[0.58684112, 0.74543947, 0.43165955, 0.1275803 ],
        [0.28377591, 0.3630823 , 0.64591724, 0.5707783 ],
        [0.35609673, 0.98651525, 0.60577482, 0.23722679],
        [0.10178247, 0.15285914, 0.24595773, 0.16068137]]])

In [60]:
Btilda

array([[0.12063587, 0.46077877, 0.20633372, 0.36426986, 0.50341727,
        0.69039483, 0.03931214, 0.7994104 , 0.62790039, 0.08175903,
        0.87357862, 0.9208724 , 0.06107796, 0.27687765, 0.80620128,
        0.74825969],
       [0.18452102, 0.20934932, 0.3704721 , 0.48452299, 0.61825477,
        0.36891364, 0.46253472, 0.74747094, 0.0366832 , 0.25243694,
        0.71334959, 0.89520684, 0.51167744, 0.53211349, 0.10717201,
        0.44741237],
       [0.53261727, 0.2424705 , 0.26924323, 0.37728416, 0.0200712 ,
        0.32207917, 0.21144801, 0.32749735, 0.11976213, 0.89052728,
        0.59359245, 0.67910232, 0.78917124, 0.4984422 , 0.08692029,
        0.53710654],
       [0.58684112, 0.74543947, 0.43165955, 0.1275803 , 0.28377591,
        0.3630823 , 0.64591724, 0.5707783 , 0.35609673, 0.98651525,
        0.60577482, 0.23722679, 0.10178247, 0.15285914, 0.24595773,
        0.16068137]])

In [68]:
B1 = np.einsum('jkl, jm ->klm ', B, Btilda) 
B2 = np.einsum('jkl, km ->jlm ', B, Btilda) 
B3 = np.einsum('jkl, lm ->jkm ', B, Btilda) 

In [70]:
B1[0]

array([[0.67666467, 0.66081431, 0.4899703 , 0.40916611, 0.35203282,
        0.53597525, 0.58176149, 0.74374859, 0.35527571, 1.10968091,
        0.90866407, 0.77719078, 0.5818398 , 0.48677045, 0.30766564,
        0.5531906 ],
       [0.66081431, 0.87061617, 0.55969189, 0.45586605, 0.57779964,
        0.74410167, 0.64770764, 1.029723  , 0.59149011, 1.04183434,
        1.14736286, 0.95322989, 0.40248617, 0.47378171, 0.59833903,
        0.68845839],
       [0.4899703 , 0.55969189, 0.43864506, 0.41131587, 0.46081672,
        0.52256952, 0.51521492, 0.7764208 , 0.32910482, 0.77599766,
        0.86583408, 0.8069011 , 0.45857905, 0.45444769, 0.33562345,
        0.53411695],
       [0.40916611, 0.45586605, 0.41131587, 0.52607513, 0.52671515,
        0.59807468, 0.40061123, 0.8497476 , 0.33711433, 0.61393561,
        0.9650906 , 1.05567437, 0.58089559, 0.56623556, 0.40977514,
        0.7124916 ]])

In [71]:
B2[0]

array([[0.47771773, 0.35875376, 0.40681612, 0.53255047, 0.40190548,
        0.49341384, 0.40981001, 0.71322504, 0.19116262, 0.75636095,
        0.87421384, 1.00265077, 0.76669305, 0.62358487, 0.22080891,
        0.66256557],
       [0.38900827, 0.58307045, 0.49237617, 0.5685305 , 0.73901609,
        0.6996776 , 0.53357361, 1.06921303, 0.42303592, 0.55790666,
        1.1112764 , 1.16357017, 0.47410606, 0.57802317, 0.52067815,
        0.74207575],
       [0.97054028, 0.91609547, 0.64034726, 0.52665157, 0.37449114,
        0.7310334 , 0.73175042, 0.94058689, 0.52270639, 1.60006893,
        1.21521814, 1.00970134, 0.80417786, 0.6367114 , 0.44478281,
        0.77072626],
       [1.12103413, 1.11627055, 0.94225251, 0.96291902, 0.90844012,
        1.11467709, 1.06210576, 1.61741083, 0.63478859, 1.78981466,
        1.88837723, 1.85395755, 1.23417486, 1.09961523, 0.643432  ,
        1.24507254]])

In [72]:
B3[0]

array([[0.42324181, 0.47362115, 0.40839145, 0.39152202, 0.45312123,
        0.45198968, 0.49678567, 0.71634739, 0.24707642, 0.66928423,
        0.77722491, 0.75011883, 0.44304722, 0.43711538, 0.25416895,
        0.46577965],
       [0.67818776, 0.98194178, 0.71530164, 0.63471277, 0.9079113 ,
        0.90516613, 0.86378742, 1.38764781, 0.63079733, 1.03907915,
        1.43986551, 1.29796777, 0.49639714, 0.6485454 , 0.67988484,
        0.8351432 ],
       [1.09652242, 1.20471105, 0.79255496, 0.71541188, 0.64549898,
        1.07937514, 0.84202432, 1.37477128, 0.82979937, 1.75837579,
        1.68323412, 1.46311226, 0.86331692, 0.79354888, 0.81740377,
        1.12358439],
       [0.92696421, 0.83936992, 0.65523556, 0.55603262, 0.43044812,
        0.67565233, 0.78425012, 0.94690353, 0.41151284, 1.53100165,
        1.18269883, 1.02910818, 0.85779315, 0.68046452, 0.33303017,
        0.72282804]])

# T1.3: Binary tensor contractions

In [157]:
##### Ex.1.3(a): Binary Tensor Contraction
d1, d2 = 2, 3

A = np.random.rand(d1, d1, d2, d2)  
B = np.random.rand(d1, d1, d2, d2)

Ap  = A.transpose(0, 2, 1, 3)
Bp = B.transpose(0, 3, 1, 2)

App = Ap.reshape(d1**2, d2**2)
Bpp = Bp.reshape(d2**2, d1**2)

# matric product
Cpp = App @ Bpp         
C   = Cpp.reshape(d1**2, d1**2)

In [152]:
A.shape, Ap.shape

((2, 2, 3, 3), (2, 3, 2, 3))

In [153]:
B.shape, Bp.shape

((2, 2, 3, 3), (2, 3, 2, 3))

In [154]:
App.shape,  Bpp.shape

((4, 9), (9, 4))

In [155]:
Cpp.shape, Cpp

((4, 4),
 array([[2.97408105, 3.41140955, 3.50621632, 2.57551422],
        [2.52385675, 2.10552156, 2.84491416, 1.87870965],
        [2.94941321, 2.74737806, 3.25295892, 2.90151594],
        [2.05128709, 2.13730638, 2.28185979, 1.65208315]]))

In [156]:
C

array([[2.97408105, 3.41140955, 3.50621632, 2.57551422],
       [2.52385675, 2.10552156, 2.84491416, 1.87870965],
       [2.94941321, 2.74737806, 3.25295892, 2.90151594],
       [2.05128709, 2.13730638, 2.28185979, 1.65208315]])

In [158]:
##### Ex.1.3(a): Binary Tensor Contraction
d = 2
A = np.random.rand(d,d,d,d)  
B = np.random.rand(d,d,d,d)

Ap  = A.transpose(0,2,1,3);  Bp = B.transpose(0,3,1,2)
App = Ap.reshape(d**2,d**2); Bpp = Bp.reshape(d**2,d**2)
Cpp = App @ Bpp;             C   = Cpp.reshape(d,d,d,d)

In [160]:
Cpp

array([[1.46515122, 0.84001427, 1.47431762, 1.29604796],
       [1.21655301, 0.51085984, 1.09943966, 1.17170796],
       [1.11192882, 0.64079906, 1.00305929, 0.85167333],
       [0.89877232, 0.24211585, 0.51707588, 0.73137655]])

In [159]:
C

array([[[[1.46515122, 0.84001427],
         [1.47431762, 1.29604796]],

        [[1.21655301, 0.51085984],
         [1.09943966, 1.17170796]]],


       [[[1.11192882, 0.64079906],
         [1.00305929, 0.85167333]],

        [[0.89877232, 0.24211585],
         [0.51707588, 0.73137655]]]])

# T1.4: Contraction costs

The computational cost of multiplying a *d1-by-d2* dimensional matrix **A** with a *d2-by-d3* dimensional matrix **B** is $\text{cost}: (A\times B) = d_1 \cdot d_2  \cdot d_3 $. Given the equivalence with matrix multiplication, this is also the cost of a binary tensor contraction (where each dimension d1, d2, d3 may now result as the product of several tensor indices from the reshapes).

 

Another way of computing the cost of contracting **A** and **B** is to take the product of the total dimensions, denoted $|dim(A)|$ and $|dim(B)|$, of each tensor divided by the total dimension of the contracted indices, denoted $|dim(A\cap B)|$. Examples are given below:

$$\text{cost}: (A\times B) = d_1 \cdot d_2  \cdot d_3 $$

$$\text{cost}: (A\times B) = \frac{d^3  d^4}{d^2} = d^5 $$

In [163]:
import time

# Inicia o cronômetro
start_time = time.time()

# O seu código aqui

##### Ex.1.4(c): Tensor network evaluation
d = 10
A = np.random.rand(d,d) 
B = np.random.rand(d,d)
C = np.random.rand(d,d)

# Evaluate network via summation over internal indices
F0 = np.zeros((d,d))
for di in range(d):
    for dj in range(d):
        for dk in range(d):
            for dl in range(d):
                F0[di,dj] = F0[di,dj] + A[di,dk]*B[dk,dl]*C[dl,dj]

# Termina o cronômetro
end_time = time.time()

# Calcula o tempo decorrido
execution_time = end_time - start_time

# Imprime o tempo de execução
print("Tempo de execução:", execution_time, "segundos")


Tempo de execução: 0.017894983291625977 segundos


In [164]:
import time

# Inicia o cronômetro
start_time = time.time()

# Seu código aqui
# Evaluate network via sequence of binary contractions
F1 = (A @ B) @ C

# Termina o cronômetro
end_time = time.time()

# Calcula o tempo decorrido
execution_time = end_time - start_time

# Imprime o tempo de execução
print("Tempo de execução:", execution_time, "segundos")


Tempo de execução: 0.0004596710205078125 segundos


In [173]:
F0

array([[14.00689909, 13.89132763, 15.35902002,  8.57673163, 15.34786475,
        15.99224679, 17.68388357, 14.66917624, 11.9954262 , 12.94473786],
       [ 8.08895146,  7.6867157 ,  8.69483168,  4.89443461,  8.75949858,
         9.11679253,  9.81675098,  8.34828549,  7.04562253,  7.17802056],
       [11.31177024, 11.46998307, 12.52815226,  6.99953937, 12.45645021,
        13.00663837, 14.47100695, 11.94011084,  9.61667395, 10.6707729 ],
       [17.25207656, 16.83364736, 19.12113685, 10.17725518, 18.72100554,
        19.35915126, 21.51256303, 17.96112081, 14.6191695 , 15.49987471],
       [12.12110545, 11.30805595, 12.9872295 ,  7.32649722, 13.30077691,
        13.93304977, 14.26151379, 12.75302016, 10.45535744, 11.12501184],
       [15.7711837 , 15.11669521, 16.92755706,  9.61846517, 17.4092709 ,
        18.08828302, 18.95904798, 16.54694723, 13.4741135 , 14.63270752],
       [16.19701723, 16.18100024, 17.49555037,  9.89346057, 18.00327986,
        18.49932735, 20.37006263, 16.82568688

In [174]:
F1

array([[14.00689909, 13.89132763, 15.35902002,  8.57673163, 15.34786475,
        15.99224679, 17.68388357, 14.66917624, 11.9954262 , 12.94473786],
       [ 8.08895146,  7.6867157 ,  8.69483168,  4.89443461,  8.75949858,
         9.11679253,  9.81675098,  8.34828549,  7.04562253,  7.17802056],
       [11.31177024, 11.46998307, 12.52815226,  6.99953937, 12.45645021,
        13.00663837, 14.47100695, 11.94011084,  9.61667395, 10.6707729 ],
       [17.25207656, 16.83364736, 19.12113685, 10.17725518, 18.72100554,
        19.35915126, 21.51256303, 17.96112081, 14.6191695 , 15.49987471],
       [12.12110545, 11.30805595, 12.9872295 ,  7.32649722, 13.30077691,
        13.93304977, 14.26151379, 12.75302016, 10.45535744, 11.12501184],
       [15.7711837 , 15.11669521, 16.92755706,  9.61846517, 17.4092709 ,
        18.08828302, 18.95904798, 16.54694723, 13.4741135 , 14.63270752],
       [16.19701723, 16.18100024, 17.49555037,  9.89346057, 18.00327986,
        18.49932735, 20.37006263, 16.82568688